name: "korza-fastmcp-boilerplate"

services:
  app:
    build:
      context: ..
      dockerfile: app-fastmcp-docker/Dockerfile
    ports:
      - "8081:8081" # MCP SSE
    volumes:
      - ./src:/app/src:Z
